### ISSUE TITLE
Not giving desired normalized text as output

### ISSUE THREAD

**Issue by ud0y** [saiful9379/pybangla#5]
My Code

```
import pybangla
nrml = pybangla.Normalizer()
text = "৫ বছরে নন-ক্যাডার পদে ৭৪৪৭ জনকে নিয়োগের সুপারিশ করা হয়েছে"
text = nrml.text_normalizer(text)

print(text)
```

Output

পাঁচ বছরে নন-ক্যাডার পদে সাত হাজার চার শত সাতচল্লিশ৪৪সাত হাজার চার শত সাতচল্লিশ জনকে নিয়োগের সুপারিশ করা হয়েছে

**Comment by saiful9379** [comment]
Thank you @ud0y for your observation, please check the updated version. this issue has been fixed.
